"""empty message

Revision ID: f94dfeb52cf6
Revises: 904f7c66f4fb
Create Date: 2021-07-12 08:32:43.999608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94dfeb52cf6'
down_revision = '904f7c66f4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('deckName', sa.String(), nullable=False))
    op.drop_constraint('decks_name_key', 'decks', type_='unique')
    op.create_unique_constraint(None, 'decks', ['deckName'])
    op.drop_column('decks', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'decks', type_='unique')
    op.create_unique_constraint('decks_name_key', 'decks', ['name'])
    op.drop_column('decks', 'deckName')
    # ### end Alembic commands ###
