"""empty message

Revision ID: a00c9bd550d9
Revises: b9001c171640
Create Date: 2021-06-07 18:12:50.204940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00c9bd550d9'
down_revision = 'b9001c171640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_dorm_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_title_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_profile_img_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'dorm_id')
    op.drop_column('users', 'profile_img')
    op.drop_column('users', 'title_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_img', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dorm_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_profile_img_fkey', 'users', 'profile_images', ['profile_img'], ['id'])
    op.create_foreign_key('users_title_id_fkey', 'users', 'titles', ['title_id'], ['id'])
    op.create_foreign_key('users_dorm_id_fkey', 'users', 'dorms', ['dorm_id'], ['id'])
    # ### end Alembic commands ###
