"""empty message

Revision ID: 904f7c66f4fb
Revises: c8e9d4c61982
Create Date: 2021-07-01 09:28:51.546128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904f7c66f4fb'
down_revision = 'c8e9d4c61982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trunk_monster_cards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monster_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_card_id'], ['monster_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'monster_card_id')
    )
    op.create_table('trunk_spell_trap_cards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spell_trap_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_trap_card_id'], ['spell_trap_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'spell_trap_card_id')
    )
    op.create_table('deck_monster_cards',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('monster_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['monster_card_id'], ['monster_cards.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'monster_card_id')
    )
    op.create_table('deck_spell_trap_cards',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('spell_trap_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['spell_trap_card_id'], ['spell_trap_cards.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'spell_trap_card_id')
    )
    op.drop_table('user_spell_trap_cards')
    op.drop_table('user_monster_cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_monster_cards',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monster_card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monster_card_id'], ['monster_cards.id'], name='user_monster_cards_monster_card_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_monster_cards_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'monster_card_id', name='user_monster_cards_pkey')
    )
    op.create_table('user_spell_trap_cards',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spell_trap_card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['spell_trap_card_id'], ['spell_trap_cards.id'], name='user_spell_trap_cards_spell_trap_card_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_spell_trap_cards_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'spell_trap_card_id', name='user_spell_trap_cards_pkey')
    )
    op.drop_table('deck_spell_trap_cards')
    op.drop_table('deck_monster_cards')
    op.drop_table('trunk_spell_trap_cards')
    op.drop_table('trunk_monster_cards')
    # ### end Alembic commands ###
