"""empty message

Revision ID: 3f4650e2caa0
Revises: a00c9bd550d9
Create Date: 2021-06-07 18:13:20.114197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4650e2caa0'
down_revision = 'a00c9bd550d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dorm_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('profile_img', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('title_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'dorms', ['dorm_id'], ['id'])
    op.create_foreign_key(None, 'users', 'profile_images', ['profile_img'], ['id'])
    op.create_foreign_key(None, 'users', 'titles', ['title_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'title_id')
    op.drop_column('users', 'profile_img')
    op.drop_column('users', 'dorm_id')
    # ### end Alembic commands ###
