"""empty message

Revision ID: 6e5313673a57
Revises: bb31b57623ca
Create Date: 2021-06-09 16:31:35.647343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5313673a57'
down_revision = 'bb31b57623ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_monster_cards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monster_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_card_id'], ['monster_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'monster_card_id')
    )
    op.create_table('user_spell_trap_cards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spell_trap_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_trap_card_id'], ['spell_trap_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'spell_trap_card_id')
    )
    op.drop_constraint('monster_cards_user_id_fkey', 'monster_cards', type_='foreignkey')
    op.drop_column('monster_cards', 'user_id')
    op.drop_constraint('spell_trap_cards_user_id_fkey', 'spell_trap_cards', type_='foreignkey')
    op.drop_column('spell_trap_cards', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell_trap_cards', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('spell_trap_cards_user_id_fkey', 'spell_trap_cards', 'users', ['user_id'], ['id'])
    op.add_column('monster_cards', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('monster_cards_user_id_fkey', 'monster_cards', 'users', ['user_id'], ['id'])
    op.drop_table('user_spell_trap_cards')
    op.drop_table('user_monster_cards')
    # ### end Alembic commands ###
