"""empty message

Revision ID: 8548623ae259
Revises: 827ce2c7fd3d
Create Date: 2021-06-09 17:30:19.088597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8548623ae259'
down_revision = '827ce2c7fd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster_cards', sa.Column('_type', sa.String(), nullable=False))
    op.add_column('monster_cards', sa.Column('attribute', sa.String(), nullable=False))
    op.add_column('monster_cards', sa.Column('race', sa.String(), nullable=False))
    op.add_column('spell_trap_cards', sa.Column('_type', sa.String(), nullable=False))
    op.add_column('spell_trap_cards', sa.Column('race', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spell_trap_cards', 'race')
    op.drop_column('spell_trap_cards', '_type')
    op.drop_column('monster_cards', 'race')
    op.drop_column('monster_cards', 'attribute')
    op.drop_column('monster_cards', '_type')
    # ### end Alembic commands ###
