"""empty message

<<<<<<< HEAD:migrations/versions/3689051acb49_.py
Revision ID: 3689051acb49
Revises: 
Create Date: 2022-03-28 20:31:12.440735
=======
Revision ID: 54d654609941
Revises: 
Create Date: 2022-03-29 00:14:27.829467
>>>>>>> refactor models. remove extra tables. change associations.:migrations/versions/54d654609941_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/3689051acb49_.py
revision = '3689051acb49'
=======
revision = '54d654609941'
>>>>>>> refactor models. remove extra tables. change associations.:migrations/versions/54d654609941_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('card_type', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('race', sa.String(length=255), nullable=False),
    sa.Column('attribute', sa.String(length=255), nullable=True),
    sa.Column('archetype', sa.String(length=255), nullable=True),
    sa.Column('card_img', sa.Text(), nullable=True),
    sa.Column('card_img_small', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('official_id')
    )
    op.create_table('dorms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profile_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_url'),
    sa.UniqueConstraint('name')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dorm_id', sa.Integer(), nullable=False),
    sa.Column('profile_img_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dorm_id'], ['dorms.id'], ),
    sa.ForeignKeyConstraint(['profile_img_id'], ['profile_images.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_trunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_deck_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_trunk_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
<<<<<<< HEAD:migrations/versions/3689051acb49_.py
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_trunk_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_card_id', sa.Integer(), nullable=False),
    sa.Column('trunk_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trunk_id'], ['trunks.id'], ),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_cards.id'], ),
=======
    sa.ForeignKeyConstraint(['user_trunk_id'], ['user_trunks.id'], ondelete='CASCADE'),
>>>>>>> refactor models. remove extra tables. change associations.:migrations/versions/54d654609941_.py
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_deck_cards')
    op.drop_table('user_trunks')
    op.drop_table('decks')
    op.drop_table('users')
    op.drop_table('titles')
    op.drop_table('profile_images')
    op.drop_table('dorms')
    op.drop_table('cards')
    # ### end Alembic commands ###
